server:
  port: 9030
  servlet:
    context-path: /spike

spring:
  application:
    name: @project.artifactId@
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
        namespace: 68bc1e7b-37af-442e-a741-0559b03a8e94
      config:
        import-check:
          enabled: false


  datasource:
    # 数据源
#    url: jdbc:mysql://192.168.25.144:3306/sunrise?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: admin
#    password: 12qw!@QW
    # 数据源
    url: jdbc:mysql://127.0.0.1:3306/sunrise?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: SunriseHikariPool
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 3000